name: Build Go pulseha
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.8'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test



name: build pulseha
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

#    - name: Test
#      run: make test

    - name: Dependencies
      run: make get

    - name: Build
      run: make